# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90dc163c46e89829be44ab5434dffb922bd5d5d0070bcf5ef68da196d8ceab1557e60f115adf5509fc330d01baadc24e28bceb518cbd66292077260e1056a93a

test:
  secret_key_base: 48d11f8ce019153b00e2ed237400fae2e5d6eb7483cf5ca647a2c6a2f9e007a200424b0b6da961fcafc48c2a185556d494a871c8c4d359cfa2cf126166a07451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
